# Generated by Django 2.0.1 on 2018-05-07 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('granthall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='receiveDate',
            new_name='orderDate',
        ),
        migrations.AddField(
            model_name='order',
            name='orderTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
