# Generated by Django 2.0.1 on 2018-05-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granthall', '0002_auto_20180507_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='espirationDate',
            new_name='expirationDate',
        ),
    ]
