# Generated by Django 2.0.1 on 2018-05-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granthall', '0003_auto_20180507_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='stockPerson',
        ),
    ]
